---
version: '3.7'
services:
    bitcoind:
        image: lncm/bitcoind:v0.21.1
        container_name: bitcoind
        hostname: bitcoind
        volumes:
            - ./data/:/data/.bitcoin
        ports:
            - 127.0.0.1:8332:8332
            - 127.0.0.1:8333:8333
            - 127.0.0.1:28332:28332
            - 127.0.0.1:28333:28333